package com.zbc.spring.cxf.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-09-05T17:08:34.713+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "userService", 
                  wsdlLocation = "http://localhost:8080/webService_CXF_demo/service/user?wsdl",
                  targetNamespace = "service.cxf.zbc.com") 
public class UserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("service.cxf.zbc.com", "userService");
    public final static QName UserServiceImplPort = new QName("service.cxf.zbc.com", "UserServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webService_CXF_demo/service/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webService_CXF_demo/service/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public IUserService getUserServiceImplPort() {
        return super.getPort(UserServiceImplPort, IUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public IUserService getUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserServiceImplPort, IUserService.class, features);
    }

}
